global:
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
   receiver: 'slack-notifications'
receivers:
 - name: 'slack-notifications'
   slack_configs:
   - channel: '#hostavtomotiv'
