version: '3.7'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VER}
    ports:
      - 9292:9292/tcp
    networks:
      reddit:
        aliases:
           - ui
  post:
    image: ${USER_NAME}/post:${POST_VER}
    networks:
      reddit:
        aliases:
           - post
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      reddit:
        aliases:
           - comment
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      reddit:
        aliases:
           - prometheus
  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
       reddit:
         aliases:
            - node-exporter 

  mongodb-exporter:
     image: ${USER_NAME}/mongodb-exporter:${MONGODB_EXPORTER_VERSION}
     networks:
        reddit:
          aliases:
             - mongodb-exporter
     environment:
          MONGODB_URI: "mongodb://post_db:27017"

volumes:
  post_db:

networks:
  reddit:
