version: '3.7'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:${UI_VER}
    ports:
      - 9292:9292/tcp
    networks:
      reddit:
        aliases:
           - ui
  post:
    image: ${USER_NAME}/post:${POST_VER}
    networks:
      reddit:
        aliases:
           - post
  comment:
    image: ${USER_NAME}/comment:${COMMENT_VER}
    networks:
      reddit:
        aliases:
           - comment
  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - 9090:9090
    networks:
      reddit:
        aliases:
           - prometheus
  node-exporter:
    image: prom/node-exporter:v0.15.0
    user: root
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
       reddit:
         aliases:
            - node-exporter 
  mongodb-exporter:
     image: ${USER_NAME}/mongodb-exporter:${MONGODB_EXPORTER_VERSION}
     networks:
        reddit:
          aliases:
             - mongodb-exporter
     environment:
          MONGODB_URI: "mongodb://post_db:27017"
  cadvisor:
     image: google/cadvisor:latest
     volumes:
         - '/:/rootfs:ro'
         - '/var/run:/var/run:rw'
         - '/sys:/sys:ro'
         - '/var/lib/docker/:/var/lib/docker:ro'
     ports:
         - 8080:8080
     networks:
       reddit:
         aliases:
            - cadvisor
              
  grafana:
     image: grafana/grafana
     volumes:
        - grafana_data:/var/lib/grafana
     environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=secret
     depends_on:
        - prometheus
     ports:
        - 3000:3000
     networks:
       reddit:
         aliases:
            - grafana

  alertmanager:
     image: ${USER_NAME}/alertmanager:latest 
     command: 
        - '--config.file=/etc/alertmanager/config.yml'
     ports: 
        - 9093:9093
     networks:
       reddit:
         aliases:
            - alertmanager

volumes:
  post_db:
  grafana_data:    

networks:
  reddit:

