---
version: '3.9'
services:
  prometheus:
    image: ${USERNAME}/prometheus
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
    ports:
      - 9090:9090
    networks:
      reddit:
        aliases:
           - prometheus
  node-exporter:
    image: prom/node-exporter:v0.15.0
    deploy:
      mode: global
    user: root
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    command:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
       reddit:
         aliases:
            - node-exporter 
  mongodb-exporter:
     image: ${USERNAME}/mongodb-exporter:${MONGODB_EXPORTER_VERSION}
     deploy:
       mode: global
     networks:
        reddit:
          aliases:
             - mongodb-exporter
     environment:
          MONGODB_URI: "mongodb://post_db:27017"
  cadvisor:
     image: google/cadvisor:latest
     deploy:
       mode: global
     volumes:
         - '/:/rootfs:ro'
         - '/var/run:/var/run:rw'
         - '/sys:/sys:ro'
         - '/var/lib/docker/:/var/lib/docker:ro'
     ports:
         - 8080:8080
     networks:
       reddit:
         aliases:
            - cadvisor
  grafana:
     image: grafana/grafana
     deploy:
       mode: global
       restart_policy:
         condition: on-failure
         max_attempts: 3
         delay: 3s
     volumes:
        - grafana_data:/var/lib/grafana
     environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=secret
#     depends_on:
#        - prometheus
     ports:
        - 3000:3000
     networks:
       reddit:
         aliases:
            - grafana
  alertmanager:
     image: ${USERNAME}/alertmanager:latest 
     deploy:
       mode: global
     command: 
        - '--config.file=/etc/alertmanager/config.yml'
     ports: 
        - 9093:9093
     networks:
       reddit:
         aliases:
            - alertmanager

volumes:
  grafana_data:    

networks:
  reddit:

