---
version: '3.9'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    deploy:
      resources:
        limits:
#          cpus: 0.25
          memory: 150M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
      mode: replicated
      update_config:
        delay: 5s
        parallelism: 1
        failure_action: pause
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    deploy:
      resources:
        limits:
#          cpus: 0.30
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 1s
      mode: replicated
      update_config:
        delay: 10s
        parallelism: 1
        failure_action: rollback
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    deploy:
      resources:
        limits:
#          cpus: 0.35
          memory: 300M
      restart_policy:
        condition: on-failure
        max_attempts: 15
        delay: 1s
      mode: replicated
      update_config:
        delay: 10s
        parallelism: 1
        failure_action: rollback
      replicas: 2
      placement:
        constraints:
          - node.role == worker
    networks:
      - reddit
volumes:
  post_db:

networks:
  reddit:

